### ISSUE TITLE
Fork samber/celery-prometheus-exporter

### ISSUE THREAD

**Issue by samber** [zerok/celery-prometheus-exporter#1]
Hi @zerok,

Thanks for you great work !

I needed to fork your project: I made some major improvements that would prevent any upgrade.

You can see my changes here: https://github.com/samber/celery-prometheus-exporter/commit/8b465213743414f261c8a9ab9812e5214e8a4ca9

**Comment by zerok** [comment]
Hi @samber,

I'm glad that the initial code at least turned out to be inspirational :)  I saw that you provide two docker images (one for Celery 3.x and one for 4.x). That's something I also have planned for the next couple of days as we are moving one of our internal applications over to 4 :)

**Comment by samber** [comment]
I just met the case where my workers, producers and celerybeat died at the same time, because of a poor testing environment.

Because the worker pool size is set when event is triggered, the exporter has been unable to update the metric from _process_event.

I made a dirty fix: https://github.com/samber/celery-prometheus-exporter/commit/637c64bfdc84380544d005b2c390a3643b2ad1ff 💩 😱 :trollface:

**Comment by zerok** [comment]
Hm... that's a weird one. Did you also consider doing the pinging in a separate thread (not the Prometheus client's)?

**Comment by samber** [comment]
With a timer ?
mmh yes, it would be cleaner !

**Comment by samber** [comment]
Done

**Comment by zerok** [comment]
Awesome :) Sorry for the late response. If you have some time available, would you like to convert this change into a PR for proper attribution? :)
