### ISSUE TITLE
Simplifying base.txt

### ISSUE THREAD

**Issue by jmdacruz** [zerok/celery-prometheus-exporter#16]
I think you can leave the `prometheus_client ` requirement out of the [base.txt](https://github.com/zerok/celery-prometheus-exporter/blob/master/requirements/base.txt#L2) file, since that's going to be installed indirectly because it's a requirement in [setup.py](https://github.com/zerok/celery-prometheus-exporter/blob/master/setup.py#L31) already.

**Comment by zerok** [comment]
The reason for the duplication is that we want to be as specific as possible for the Docker images but stay flexible for people installing this via pip :)
