### ISSUE TITLE
Create Docker Hub autobuild

### ISSUE THREAD

**Issue by nailgun** [zerok/celery-prometheus-exporter#23]
Please create automatic build on Docker Hub. I suppose it to have two tags: celery-3 and celery-4.

![image](https://user-images.githubusercontent.com/100317/32713906-696ac4e0-c85c-11e7-94e8-e6a6af9e103d.png)

I've forked the repo just to create the one: https://hub.docker.com/r/smpio/celery-prometheus-exporter/

**Comment by zerok** [comment]
This has been on my list for quite some time now :) Perhaps I will get around to finally set that up tonight or tomorrow :(

**Comment by zerok** [comment]
Done :) https://hub.docker.com/r/zerok/celery-prometheus-exporter/

Thank you for the hint!
