### ISSUE TITLE
Tasks metrics are all zero

### ISSUE THREAD

**Issue by Emerson** [zerok/celery-prometheus-exporter#26]
Howdy,

This library does exactly what we need, but we're getting all zeros for our metrics. The metrics and tasks are listed correctly, so we know the redis connection is working, but the values are just 0 and never change.

We're working on this problem, but if anyone has dealt with this I'd love some help.

We're running Celery 3.x, Python 2.7, and the `master` branch of celery-prometheus-exporter.

**Comment by zerok** [comment]
Could it be that you have events disabled in your Celery setup? The readme has some hints about that 🙂

Other than that, how are you using the exporter? Inside Docker, the release version, …? 🙂

**Comment by Emerson** [comment]
Hey – we finally got this working and I wanted to let you know how we resolved the problem.

We are using **Python 2.7** on **Django 1.8**, so we're running on the latest commit from the `master` branch and using PIP to install `celery-prometheus-exporter`. We definitely had events enabled.

It seemed like no matter what we did, we could not get metrics for our tasks. Finally, we ended up **bumping our version of Celery from 3.1 to 4.1** and this appears to have fixed the problem. Thankfully, the upgrade was pretty straightforward _(required a couple config changes)_.

Anyways, feel free to close this issue. I just wanted other people to know what we did to resolve things.

**Comment by zerok** [comment]
Hi :) Sorry for the late response. Great that you got it working! I think this means that we should also try to provide a Celery 4.x-compatible version of this package. If you don't mind then I will close this ticket and create a new one dedicated to 4.x-support 😄
