### ISSUE TITLE
Pulling celery metrics for *only* the current machine

### ISSUE THREAD

**Issue by Drewster727** [zerok/celery-prometheus-exporter#29]
Just wanted to start by saying thank you for making this.

Background:
I have 5+ instances in AWS that auto-scale, meaning they spin up and down based on load. Each of the boxes runs celery workers to process data. They all connect to a rabbitmq broker.

I've been testing this exporter on one of the boxes and have noticed that it's pulling all kinds of metrics even when I stop all of this particular box's workers. Does this mean it's talking to rabbit and just pulling all worker metrics?

I was under the assumption that it would only be pulling celery metrics for the *current* node it is installed on. Can you shed some light on this?

Thanks!

**Comment by Drewster727** [comment]
Unless I'm misunderstanding and the exporter should just live on the broker -- in which case I have two rabbitmq boxes that are load balanced, making this a bit more complicated

**Comment by zerok** [comment]
Hi :) Sorry for the late response. If possible, can you please provide a docker-compose file with such a setup so that I can reproduce your situation more easily? :)
