### ISSUE TITLE
Celery has to be configured to send events

### ISSUE THREAD

**Issue by rangermeier** [zerok/celery-prometheus-exporter#3]
The documentation mentions nowhere that celery has to be configured to send task events. Took me some time to figure it out. It would be nice if the exporter could check on start if this option is enabled in the celery app.

Relevant documentation: http://docs.celeryproject.org/en/latest/userguide/configuration.html#worker-send-task-events and http://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html#cmdoption-celery-worker-e

**Comment by zerok** [comment]
Would you like to create a pull-request with your proposed changes?

**Comment by rangermeier** [comment]
As I couldn't figure out if and how the exporter can inspect the configuration of the workers, I submitted a PR with the simple solution: just mention it in the docs.

**Comment by zerok** [comment]
Yes, IMHO a documentation-solution is better than some magic but might bite us later on 😃 Thank you!
