### ISSUE TITLE
How to add more metrics?

### ISSUE THREAD

**Issue by miguelHx** [zerok/celery-prometheus-exporter#30]
Hi. How can we add more metrics such as time taken to complete a task, load average, etc.

**Comment by zerok** [comment]
Hi :)

This exporter is currently not modular enough to support adding metrics without also modifying the core component, so you will most likely have to modify the `setup_metrics` function and either the `MonitorThread` or the `WorkerMonitoringThread` class to expose all the metrics that you want :)

**Comment by miguelHx** [comment]
Okay, thank you for the pointers! :)

**Comment by zerok** [comment]
You’re welcome 😊 


On Mon, Jun 18, 2018, at 19:49, Miguel Hernandez wrote:
> Okay, thank you for the pointers! :)


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/zerok/celery-prometheus-exporter/issues/30#issuecomment-398139244
