### ISSUE TITLE
Strange metrics behaviour

### ISSUE THREAD

**Issue by ryannealmes** [zerok/celery-prometheus-exporter#37]
I am trying to understand how to use this exporter effectively. Right now I have a graph with the different metric states. The strange thing is that I am only getting activity for the success state. Everything else is flat?

Wouldn't `received` or `pending` have spikes over time? Any insight into why this might be happening would be appreciated.

<img width="649" alt="screen shot 2019-01-11 at 16 08 32" src="https://user-images.githubusercontent.com/5302894/51065729-3abc5700-15bb-11e9-9f3c-7b63d0c09da7.png">

**Comment by javabrett** [comment]
The state metric should be cumulative and point-in-time ... so unless you expect to find tasks blocked in a received or pending state, then you would only expect to see tasks in the `SUCCESS` state.  In other words, in a non-overloaded system, tasks will only be in `RECEIVED` or `PENDING` for very short periods until a worker starts them, and if the tasks are short, they won't be in `STARTED` very long either.

Unless you happen to sample while a task is executing, you might only see tasks in the `SUCCEEDED` state.

**Comment by ryannealmes** [comment]
Thx that makes sense.
