### ISSUE TITLE
Queue Length Monitoring (I know, again)

### ISSUE THREAD

**Issue by gcavalcante8808** [zerok/celery-prometheus-exporter#41]
Hi,

We just started to use the celery-prometheus-exporter and it is awesome! But now, we need to monitor our queue as well, because sometimes our autoscalers aren't triggering the scale on k8s in the speed that is needed.

I'm aware of an ancient issue https://github.com/zerok/celery-prometheus-exporter/issues/17 about the queue length monitoring and it was finished because there is no way on how to make the code agnostic about the broker.

But today, looking at https://stackoverflow.com/questions/18631669/django-celery-get-task-count, there is a example with the following code (I just tested against a redis instance and its working, from https://stackoverflow.com/questions/18631669/django-celery-get-task-count):
```
celery = Celery(app)

with celery.connection_or_acquire() as conn:
    conn.default_channel.queue_declare(queue='my-queue', passive=True).message_count
```
Additionally, Looking at `https://github.com/Bahus/celery-prometheus-exporter` there is a QueueMonitorThread that could be modified to use the app. What do you think?

If needed I can make a PR for this.

**Comment by zerok** [comment]
Personally, it'd love to have that as part of this exporter :) As this requires some low-level interaction with the underlying message broker, it would IMO make sense to just expose the counter if the broker is supported. For instance, if Celery were configured to use Redis, then something like `celery_queue_lengths{queue="name"}` would be exposed, otherwise not.

If you can find to write a PR then that would be awesome! Thank you :)

**Comment by kelvan** [comment]
Now as this feature is merged, are there already plans for a new release?

**Comment by zerok** [comment]
Sorry about the delay :) 1.6.0 is now on pypi and on https://hub.docker.com/r/zerok/celery-prometheus-exporter/tags :)

**Comment by kelvan** [comment]
That's great, thank you. :)

**Comment by rei-ifesca** [comment]
Already in use, it works :)

**Comment by zerok** [comment]
> Already in use, it works :)

Awesome! Thanks for live-testing 😄

**Comment by rei-ifesca** [comment]
@zerok regarding dynamic queue names, take a look at this solution: https://github.com/Bahus/celery-prometheus-exporter/blob/3d7eec01aa3fcad47aa0a62bcba364b06eae3ad5/celery_prometheus_exporter/main.py#L189
