### ISSUE TITLE
Where is `1.6.0-celery3` docker image?

### ISSUE THREAD

**Issue by gcavalcante8808** [zerok/celery-prometheus-exporter#47]
Hi,

Currently only images for celery 4 containing the 1.6.0 release are published. Can you publish the `1.6.0-celery4` image tag as well?

![image](https://user-images.githubusercontent.com/640897/55430054-7421b480-5563-11e9-8a2e-b02b163ba9f3.png)

Thank you!

**Comment by zerok** [comment]
Done, sorry :)
