### ISSUE TITLE
problem installing with pip

### ISSUE THREAD

**Issue by yosefy** [zerok/celery-prometheus-exporter#6]
Python 2.7.3

root@ip-172-31-25-86:~# pip install celery-prometheus-exporter
Downloading/unpacking celery-prometheus-exporter
  Downloading celery-prometheus-exporter-1.1.0.tar.gz
  Running setup.py egg_info for package celery-prometheus-exporter

Requirement already satisfied (use --upgrade to upgrade): celery>=3 in /usr/local/lib/python2.7/dist-packages (from celery-prometheus-exporter)
Downloading/unpacking prometheus-client (from celery-prometheus-exporter)
  Downloading prometheus_client-0.0.19.tar.gz
  Running setup.py egg_info for package prometheus-client

Requirement already satisfied (use --upgrade to upgrade): pytz>dev in /usr/local/lib/python2.7/dist-packages (from celery>=3->celery-prometheus-exporter)
Requirement already satisfied (use --upgrade to upgrade): billiard>=3.3.0.23,<3.4 in /usr/local/lib/python2.7/dist-packages (from celery>=3->celery-prometheus-exporter)
Requirement already satisfied (use --upgrade to upgrade): kombu>=3.0.34,<3.1 in /usr/local/lib/python2.7/dist-packages (from celery>=3->celery-prometheus-exporter)
Requirement already satisfied (use --upgrade to upgrade): anyjson>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from kombu>=3.0.34,<3.1->celery>=3->celery-prometheus-exporter)
Requirement already satisfied (use --upgrade to upgrade): amqp>=1.4.9,<2.0 in /usr/local/lib/python2.7/dist-packages (from kombu>=3.0.34,<3.1->celery>=3->celery-prometheus-exporter)
Installing collected packages: celery-prometheus-exporter, prometheus-client
  Running setup.py install for celery-prometheus-exporter
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/celery_prometheus_exporter.py', 34, 33, '    def __init__(self, *args, app=None, **kwargs):\n'))

**Comment by zerok** [comment]
Hi 🙂

Sorry, but Python 2.x is not supported.
